export const overviewAssets = {
  todaySummaryDuck: require("../../../demos/assets/today-summary-duck-frames.png"),
  weeklyDuck: require("../../../demos/assets/weekly-report-duck-frames.png"),
  monthlyDuck: require("../../../demos/assets/monthly-report-duck-frames.png"),
  allReportDuck: require("../../../demos/assets/all-report-duck-frames.png"),
  milestoneDuck: require("../../../demos/assets/milestone-intro-duck-frames.png"),
  milestoneSheetDuck: require("../../../demos/assets/milestone-sheet-duck-frames.png"),
  growthAiDuck: require("../../../demos/assets/growth-ai-duck-frames.png"),
  rhythmIdle: require("../../../demos/assets/rhythm-duck-idle.png"),
  rhythmFeed: require("../../../demos/assets/rhythm-duck-feed.png"),
  rhythmDiaper: require("../../../demos/assets/rhythm-duck-diaper.png"),
  rhythmRest: require("../../../demos/assets/rhythm-duck-rest.png"),
  weightMotion: [
    require("../../../demos/assets/weight-motion-01.png"),
    require("../../../demos/assets/weight-motion-02.png"),
    require("../../../demos/assets/weight-motion-03.png"),
    require("../../../demos/assets/weight-motion-04.png"),
    require("../../../demos/assets/weight-motion-05.png"),
    require("../../../demos/assets/weight-motion-06.png"),
    require("../../../demos/assets/weight-motion-07.png"),
    require("../../../demos/assets/weight-motion-08.png"),
  ],
  heightMotion: [
    require("../../../demos/assets/height-motion-01.png"),
    require("../../../demos/assets/height-motion-02.png"),
    require("../../../demos/assets/height-motion-03.png"),
    require("../../../demos/assets/height-motion-04.png"),
    require("../../../demos/assets/height-motion-05.png"),
    require("../../../demos/assets/height-motion-06.png"),
    require("../../../demos/assets/height-motion-07.png"),
    require("../../../demos/assets/height-motion-08.png"),
  ],
  headMotion: [
    require("../../../demos/assets/head-motion-01.png"),
    require("../../../demos/assets/head-motion-02.png"),
    require("../../../demos/assets/head-motion-03.png"),
    require("../../../demos/assets/head-motion-04.png"),
    require("../../../demos/assets/head-motion-05.png"),
    require("../../../demos/assets/head-motion-06.png"),
    require("../../../demos/assets/head-motion-07.png"),
    require("../../../demos/assets/head-motion-08.png"),
  ],
} as const;
