export const PARENTS = [
  {
    id: 1,
    name: { en: 'Jieun Kim', ko: '김지은' },
    avatar: '👩',
    location: 'Capitol Hill, Seattle',
    languages: ['Korean', 'English'],
    verified: true,
    dueDate: { en: 'Aug 15, 2026', ko: '2026년 8월 15일' },
    liveIn: true,
    budget: '$1,500 – $2,000 / wk',
    newbornExp: true,
    nonSmoker: true,
    breastfeeding: true,
    notes: { en: 'First-time parents, very hands-on. Looking for warm, patient caregiver.', ko: '첫째 아이입니다. 따뜻하고 인내심 있는 분을 원해요.' },
  },
  {
    id: 2,
    name: { en: 'Soyeon Park', ko: '박소연' },
    avatar: '👩‍👦‍👦',
    location: 'South Bellevue, WA',
    languages: ['Korean'],
    verified: true,
    dueDate: { en: 'Sep 3, 2026', ko: '2026년 9월 3일' },
    liveIn: true,
    budget: '$2,000 – $2,500 / wk',
    newbornExp: true,
    nonSmoker: true,
    breastfeeding: false,
    notes: { en: 'Twins expected. Needs experienced caregiver, Korean-speaking preferred.', ko: '쌍둥이 출산 예정입니다. 경험 많으신 분 선호해요.' },
  },
  {
    id: 3,
    name: { en: 'Minjung Lee', ko: '이민정' },
    avatar: '👩‍💻',
    location: 'Redmond, WA',
    languages: ['English', 'Korean'],
    verified: false,
    dueDate: { en: 'Jul 28, 2026', ko: '2026년 7월 28일' },
    liveIn: false,
    budget: '$1,200 – $1,600 / wk',
    newbornExp: true,
    nonSmoker: false,
    breastfeeding: false,
    notes: { en: 'Work-from-home mom, needs daytime support Mon–Fri.', ko: '재택근무 중이라 평일 낮 도움이 필요해요.' },
  },
];
