import { StyleSheet } from "react-native";
import { colors, radius } from "../../../theme";

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: colors.background },
  header: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 16,
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: colors.border,
  },
  headerBtn: { fontSize: 15, fontWeight: "600", color: colors.muted },
  headerBtnHit: { minHeight: 44, minWidth: 56, justifyContent: "center" },
  headerTitle: { fontSize: 16, fontWeight: "800", color: colors.text },
  headerSpacer: { minWidth: 48 },
  headerModeBtn: { minHeight: 44, minWidth: 64, alignItems: "flex-end", justifyContent: "center" },
  content: { paddingHorizontal: 18, paddingTop: 16 },
  hint: { fontSize: 13, color: colors.muted, lineHeight: 19, marginBottom: 14 },
  hintMuted: { fontSize: 12, color: colors.faint, marginTop: 10 },
  card: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: radius.lg,
    padding: 14,
    marginBottom: 10,
  },
  cardPrimary: { backgroundColor: colors.amber, borderColor: colors.amber },
  cardCopy: { flex: 1, minWidth: 0 },
  cardTitle: { fontSize: 15, fontWeight: "800", color: colors.text },
  cardTitlePrimary: { color: colors.brandCoralForeground },
  cardBody: { fontSize: 12.5, color: colors.muted, marginTop: 4, lineHeight: 18 },
  label: { fontSize: 13, fontWeight: "700", color: colors.text, marginBottom: 8 },
  sectionTitle: { fontSize: 17, fontWeight: "800", color: colors.text, marginBottom: 8 },
  input: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: colors.text,
  },
  textArea: { minHeight: 110, textAlignVertical: "top" },
  coverPreview: { width: "100%", height: 220, borderRadius: 16, marginBottom: 12 },
  coverTemplatePreview: {
    width: "100%",
    aspectRatio: 210 / 297,
    maxHeight: 280,
    borderRadius: 16,
    overflow: "hidden",
    marginBottom: 12,
  },
  coverPlaceholder: {
    height: 160,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: colors.border,
    borderStyle: "dashed",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 12,
    backgroundColor: colors.cardHi,
  },
  coverPlaceholderText: { color: colors.faint, fontWeight: "600" },
  primaryBtn: {
    backgroundColor: colors.primary,
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
    marginTop: 8,
  },
  primaryBtnText: { color: colors.primaryForeground, fontWeight: "800", fontSize: 14.5 },
  secondaryBtn: {
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.card,
    borderRadius: 14,
    paddingVertical: 13,
    alignItems: "center",
    marginTop: 8,
  },
  secondaryBtnText: { color: colors.text, fontWeight: "700", fontSize: 14 },
  ghostBtn: { paddingVertical: 14, alignItems: "center", marginTop: 4 },
  ghostBtnText: { color: colors.amberText, fontWeight: "700" },
  poolRow: { gap: 8, paddingRight: 8 },
  poolThumbWrap: { borderRadius: 12, borderWidth: 2, borderColor: "transparent", overflow: "hidden" },
  poolThumbSelected: { borderColor: colors.amber },
  poolThumb: { width: 72, height: 72, borderRadius: 10 },
  index: { width: 18, fontSize: 12, fontWeight: "800", color: colors.faint },
  thumb: { width: 52, height: 52, borderRadius: 12 },
  thumbPlaceholder: {
    width: 52,
    height: 52,
    borderRadius: 12,
    backgroundColor: colors.cardHi,
    alignItems: "center",
    justifyContent: "center",
  },
  thumbFallback: { fontSize: 18 },
  photoEditWrap: { width: 84 },
  photoActions: { flexDirection: "row", flexWrap: "wrap", gap: 4, marginTop: 6 },
  miniChip: {
    backgroundColor: colors.cardHi,
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  miniChipDanger: { backgroundColor: colors.dangerSoft },
  miniChipText: { fontSize: 10, fontWeight: "700", color: colors.text },
  addPhotoTile: {
    width: 72,
    height: 72,
    borderRadius: 12,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: colors.amber,
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: colors.amberSoft,
  },
  addPhotoText: { color: colors.amberText, fontWeight: "800", fontSize: 12 },
  layoutRow: { flexDirection: "row", flexWrap: "wrap", gap: 8 },
  layoutChip: {
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: colors.card,
  },
  layoutChipSelected: { backgroundColor: colors.amberSoft, borderColor: colors.amber },
  layoutChipDisabled: { opacity: 0.35 },
  layoutChipText: { fontSize: 12.5, fontWeight: "700", color: colors.muted },
  layoutChipTextSelected: { color: colors.amberText },
  pageWorkspace: { flex: 1, backgroundColor: "#E9E2DA" },
  editorReaderWrap: { flex: 1, paddingTop: 12, paddingBottom: 8 },
  editorReader: { flex: 1 },
  canvasStage: { flex: 1, alignItems: "center", justifyContent: "center", paddingHorizontal: 6, paddingTop: 4, overflow: "hidden" },
  pageSlideSurface: {
    width: "100%",
    alignItems: "center",
    justifyContent: "center",
  },
  editorCanvas: {
    width: "96%",
    maxWidth: 430,
    shadowColor: "#4A3428",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 8,
  },
  bookNavigation: { borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: "rgba(255,249,242,0.96)", paddingBottom: 5 },
  pageNavigator: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8 },
  pageArrow: { width: 44, height: 44, alignItems: "center", justifyContent: "center" },
  pageArrowPrev: { transform: [{ rotate: "180deg" }] },
  pageCounter: { minWidth: 56, textAlign: "center", fontSize: 12, fontWeight: "800", color: colors.muted },
  pageChipRow: { minHeight: 44, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, paddingHorizontal: 8, paddingVertical: 4 },
  pageChip: { minWidth: 44, minHeight: 44, paddingHorizontal: 12, borderRadius: 22, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, backgroundColor: colors.card },
  pageChipActive: { borderColor: colors.amber, backgroundColor: colors.amberSoft },
  pageChipText: { fontSize: 11, fontWeight: "700", color: colors.muted },
  pageChipTextActive: { color: colors.amberText },
  pageEllipsis: { width: 16, textAlign: "center", color: colors.faint, fontSize: 14, fontWeight: "800" },
  editorToolbar: {
    minHeight: 60,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-around",
    paddingHorizontal: 6,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    backgroundColor: colors.card,
  },
  editorToolbarCompact: { minHeight: 56, flexDirection: "row", alignItems: "center", justifyContent: "center", paddingHorizontal: "24%", borderTopWidth: 1, borderTopColor: colors.border, backgroundColor: colors.card },
  editorTool: { flex: 1, minHeight: 44, alignItems: "center", justifyContent: "center", gap: 3, paddingVertical: 7 },
  editorToolLabel: { fontSize: 10.5, color: colors.text, fontWeight: "700" },
  sheetOverlay: { ...StyleSheet.absoluteFillObject, zIndex: 30, justifyContent: "flex-end", backgroundColor: "rgba(42,36,31,0.42)" },
  editorSheet: { maxHeight: "72%", borderTopLeftRadius: 24, borderTopRightRadius: 24, backgroundColor: colors.background, paddingHorizontal: 18, paddingTop: 10 },
  sheetHandle: { width: 44, height: 5, borderRadius: 3, alignSelf: "center", backgroundColor: colors.border, marginBottom: 10 },
  sheetHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  sheetTitle: { fontSize: 18, fontWeight: "800", color: colors.text },
  sheetClose: { fontSize: 13, fontWeight: "700", color: colors.muted },
  sheetHint: { fontSize: 12, lineHeight: 18, color: colors.muted, marginBottom: 10 },
  sheetScroll: { maxHeight: 390 },
  photoSheetRow: { minHeight: 68, flexDirection: "row", alignItems: "center", gap: 10, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 8, marginBottom: 8, backgroundColor: colors.card },
  photoSheetRowSelected: { borderColor: colors.amber, backgroundColor: colors.amberSoft },
  photoSheetThumb: { width: 50, height: 50, borderRadius: 9 },
  photoSheetEmpty: { width: 50, height: 50, borderRadius: 9, borderWidth: 1, borderStyle: "dashed", borderColor: colors.amber, alignItems: "center", justifyContent: "center" },
  photoSheetLabel: { flex: 1, fontSize: 13, fontWeight: "700", color: colors.text },
  sheetAction: { fontSize: 12, color: colors.amberText, fontWeight: "800", paddingVertical: 8 },
  sheetDanger: { color: colors.dangerText },
  sheetOptionGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10, paddingBottom: 8 },
  sheetOption: { width: "48%", minHeight: 118, borderWidth: 1, borderColor: colors.border, borderRadius: 16, backgroundColor: colors.card, alignItems: "center", justifyContent: "center", gap: 8, padding: 10 },
  sheetOptionSelected: { borderColor: colors.amber, backgroundColor: colors.amberSoft },
  layoutThumbnail: { position: "relative", width: 72, height: 48 },
  layoutThumbnailSlot: { position: "absolute", borderRadius: 3, borderWidth: 1, borderColor: colors.border, backgroundColor: "#F3E8DA" },
  layoutThumbnailSlotSelected: { borderColor: colors.amber, backgroundColor: "rgba(232,145,138,0.28)" },
  sheetOptionText: { fontSize: 11.5, lineHeight: 15, fontWeight: "700", color: colors.muted, textAlign: "center" },
  sheetOptionTextSelected: { color: colors.amberText },
  ratioOptionSection: { width: "100%", borderWidth: 1, borderColor: colors.border, borderRadius: 14, backgroundColor: colors.card, padding: 12, marginTop: 2 },
  ratioOptionHeader: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginBottom: 8 },
  ratioOptionTitle: { fontSize: 12.5, fontWeight: "800", color: colors.text },
  ratioOptionValue: { fontSize: 11, fontWeight: "800", color: colors.amberText },
  ratioOptionRow: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
  ratioChip: { minWidth: 46, height: 30, paddingHorizontal: 8, borderRadius: 15, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, backgroundColor: colors.cardHi },
  ratioChipSelected: { borderColor: colors.amber, backgroundColor: colors.amberSoft },
  ratioChipText: { fontSize: 11, fontWeight: "700", color: colors.muted },
  ratioChipTextSelected: { color: colors.amberText },
  ratioOptionHint: { marginTop: 7, fontSize: 10.5, lineHeight: 15, color: colors.faint },
  sheetTextArea: { minHeight: 112, textAlignVertical: "top" },
  commentStickerHeader: { marginTop: 10, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  commentStickerTitle: { fontSize: 13, fontWeight: "800", color: colors.text },
  commentStickerAdd: { borderWidth: 1, borderColor: colors.amber, borderRadius: 999, paddingHorizontal: 10, paddingVertical: 7, backgroundColor: colors.amberSoft },
  commentStickerAddText: { fontSize: 11, fontWeight: "800", color: colors.amberText },
  commentStickerList: { paddingTop: 8, paddingRight: 8, gap: 8 },
  commentStickerChip: { width: 74, minHeight: 70, alignItems: "center", justifyContent: "center", borderWidth: 1, borderColor: colors.border, borderRadius: 12, backgroundColor: colors.card },
  commentStickerRemove: { position: "absolute", top: 3, right: 3, zIndex: 5, elevation: 5, width: 20, height: 20, borderRadius: 10, alignItems: "center", justifyContent: "center", backgroundColor: colors.dangerText },
  commentStickerRemoveText: { color: "#FFF", fontSize: 14, fontWeight: "900", lineHeight: 17 },
  commentStickerEmpty: { marginTop: 8, fontSize: 11, color: colors.faint },
  sheetPrimary: { backgroundColor: colors.primary, minHeight: 48, borderRadius: 14, alignItems: "center", justifyContent: "center", marginTop: 10, marginBottom: 8 },
  sheetPrimaryText: { color: colors.primaryForeground, fontWeight: "800", fontSize: 14 },
  rollingSheetCard: { backgroundColor: colors.card, borderWidth: 1, borderColor: colors.border, borderRadius: 14, padding: 12, marginBottom: 8 },
  rollingStickerPreviewRow: { marginTop: 6, minHeight: 34, flexDirection: "row", flexWrap: "wrap", alignItems: "center", gap: 4 },
  pdfCanvasWrap: { alignItems: "center", marginBottom: 12 },
  pdfCanvasPreview: { width: "76%", maxWidth: 320, shadowColor: "#4A3428", shadowOpacity: 0.16, shadowRadius: 10, shadowOffset: { width: 0, height: 6 }, elevation: 5 },
  autoAuthor: { fontSize: 13, fontWeight: "800", color: colors.amberText, marginBottom: 8, marginTop: 8 },
  commentCard: {
    backgroundColor: colors.card,
    borderWidth: 1,
    borderColor: colors.border,
    borderRadius: 14,
    padding: 12,
    marginBottom: 8,
  },
  commentAuthor: { fontSize: 12.5, fontWeight: "800", color: colors.amberText },
  commentText: { fontSize: 13.5, color: colors.text, marginTop: 6, lineHeight: 20 },
  commentActions: { flexDirection: "row", gap: 14, marginTop: 10 },
  commentAction: { fontSize: 12, fontWeight: "700", color: colors.muted },
  commentDanger: { color: colors.dangerText },
});
